//
// Generated file, do not edit! Created by opp_msgtool 6.3 from src/messages/VehicleStatusMessage.msg.
//

#ifndef __VEINS_VEHICLESTATUSMESSAGE_M_H
#define __VEINS_VEHICLESTATUSMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class VehicleStatusMessage;

}  // namespace veins

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4


namespace veins {

/**
 * Class generated from <tt>src/messages/VehicleStatusMessage.msg:5</tt> by opp_msgtool.
 * <pre>
 * packet VehicleStatusMessage extends BaseFrame1609_4
 * {
 *     int senderId;
 *     int serial;
 *     string vehicleId;
 * 
 *     double posX;
 *     double posY;
 *     double speed;
 * 
 *     simtime_t creationTime;
 * }
 * </pre>
 */
class VehicleStatusMessage : public ::veins::BaseFrame1609_4
{
  protected:
    int senderId = 0;
    int serial = 0;
    ::omnetpp::opp_string vehicleId;
    double posX = 0;
    double posY = 0;
    double speed = 0;
    ::omnetpp::simtime_t creationTime = SIMTIME_ZERO;

  private:
    void copy(const VehicleStatusMessage& other);

  protected:
    bool operator==(const VehicleStatusMessage&) = delete;

  public:
    VehicleStatusMessage(const char *name=nullptr, short kind=0);
    VehicleStatusMessage(const VehicleStatusMessage& other);
    virtual ~VehicleStatusMessage();
    VehicleStatusMessage& operator=(const VehicleStatusMessage& other);
    virtual VehicleStatusMessage *dup() const override {return new VehicleStatusMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);

    virtual int getSerial() const;
    virtual void setSerial(int serial);

    virtual const char * getVehicleId() const;
    virtual void setVehicleId(const char * vehicleId);

    virtual double getPosX() const;
    virtual void setPosX(double posX);

    virtual double getPosY() const;
    virtual void setPosY(double posY);

    virtual double getSpeed() const;
    virtual void setSpeed(double speed);

    virtual ::omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(::omnetpp::simtime_t creationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const VehicleStatusMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, VehicleStatusMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::VehicleStatusMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::VehicleStatusMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_VEHICLESTATUSMESSAGE_M_H

